### ISSUE TITLE
gulp test throws errors

### ISSUE THREAD

**Issue by atgillette** [thaiat/generator-angular-famous-ionic#119]
Hi,

I've attempted to run gulp test after setting up the project and I'm getting this error:

[21:13:14] (ERROR) karma
[21:13:14] 'karma' errored after 3.5 s
[21:13:14] Error in plugin 'gulp-karma'
karma exited with code 1
[21:13:14] 'test' errored after 4.96 s
[21:13:14] Error: [object Object]

It looks like karma is not finding the tests in the client code folder.

**Comment by thaiat** [comment]
Hi @atgillette 
can you upload your project somewhere so i could have a look ?

**Comment by atgillette** [comment]
You can access it here, https://github.com/atgillette/test-angular-famous-ionic <https://github.com/atgillette/test-angular-famous-ionic>.

**Comment by thaiat** [comment]
i see, you didn't yet scaffolded any component in your project, so gulp-karma is complaining as it does not have any test to run (main.test.js is ignored).
try the following:
```
yo angular-famous-ionic:module common
yo angular-famous-ionic:controller common home
```
This will create a common module with one home controller

try running the test again, it should work

**Comment by atgillette** [comment]
Thanks for getting back me.  What’s the reason for ignoring main.test.js.  There’s certainly code in there that should be tested.

Adrian

**Comment by thaiat** [comment]
well at some point i had issue with karma trying to load multiple times the same files are they are both required by main and by component test file.
you can try removing line 23 of karma.conf.js (https://github.com/atgillette/test-angular-famous-ionic/blob/master/karma.conf.js#L23) and let me know if it worked

**Comment by atgillette** [comment]
Sill no tests ran.

**Comment by thaiat** [comment]
just cloned your repo and made the change, it s working for me
![karma](https://cloud.githubusercontent.com/assets/4806944/6023606/48ba5236-abce-11e4-8d63-027409547122.png)

can you add me as a collaborator to your repo so i'll push my change in a new branch ?
or do you wanna chat on skype ?

**Comment by thaiat** [comment]
i confirm that this change in karma.conf.js fixes  the issue
