### ISSUE TITLE
famous-flex third party dependency

### ISSUE THREAD

**Issue by matt-d-rat** [thaiat/generator-angular-famous-ionic#126]
Hey, quick question. I want to use [famous-flex](https://github.com/IjzerenHein/famous-flex) (third party dependency) with your awesome generator. I have followed the steps in the Readme regarding how browsersync loads the dependency by modifying the package.json:

```
// Some code omitted
"browser": {
    "famous": "./bower_components/famous/dist/famous-global.js",
    "famous-flex": "./bower_components/famous-flex/global-no-famous.template.js"
},
"browserify-shim": {
    "famous": {
        "exports": "famous"
    },
    "famous-flex": {
        "exports": "famous-flex",
        "depends": [
            "famous-polyfills",
            "famous"
        ]
    }
}
```

Browsersync bundles successfully, but I am getting an error in the console when the ___famous-flex/global-no-famous.template.js___ tries to require in the src files:

![image](https://cloud.githubusercontent.com/assets/314505/6055657/d0c75400-ad57-11e4-8ba5-ff8e87e0295d.png)

I assume ___famous-flex/global-no-famous.template.js___ is not correctly declaring the modules, can you help me by explaining what I need to change in order to get this to load correctly.

Thanks!

**Comment by thaiat** [comment]
hi @matt-d-rat 
can you put together a repo and add me as a collaborator so i can easily reproduce ?

**Comment by matt-d-rat** [comment]
Thanks: https://github.com/matt-d-rat/generator-angular-famous-ionic-test

**Comment by thaiat** [comment]
@matt-d-rat , could not make it run either. 

But this is more an issue on the component side. Try to open issue there saying you want to use there component in a browserify application and you need some guidance.

**Comment by matt-d-rat** [comment]
@thaiat Yeah they need to implement a better minified released build. Thanks for your help. I will raise an issue there.

**Comment by matt-d-rat** [comment]
Possibly related to https://github.com/IjzerenHein/famous-flex/issues/47 - any guidance you can provide to helping me to get this to work with the aforementioned browserfiy application would be most appreciated.
