### ISSUE TITLE
cordova build error

### ISSUE THREAD

**Issue by mydearxym** [thaiat/generator-angular-famous-ionic#129]
Hi~ @thaiat 
i wanna use your cool generator to try to build my phone app
i follow the guide: 
```javascript 
yo angular-famous-ionic:target phonemonitor --mobile  // => works fine and generator some files in my client folder
```
but when i run this , i got error 
```javascript
➜ famous-angular-yo git:(master) ✗ gulp cordova:run --platform android
[08:41:12] Using gulpfile ~/code/famous-angular-yo/gulpfile.js
[08:41:12] Starting 'cordova:run'...
[08:41:12] Running task 'cordova:run' with targets app in mode dev
[08:41:12] Starting 'cordova:run:ntLal'...
[08:41:12] Error: app is not a cordova application
[08:41:12] Finished 'cordova:run:ntLal' after 763 μs
[08:41:12] Finished 'cordova:run' after 15 ms

```
so, what's the typical workflow around `cordova` staff?  kind confused ...

**Comment by thaiat** [comment]
hi @mydearxym try running
```
gulp cordova:run --target mobile --platform android
```

without target, you gulp default to the "app" target which is not mobile

**Comment by mydearxym** [comment]
hi @thaiat thanks for your patient, there is "but"  though
i still get error, lost in error description: 
```javascript 
[16:47:07] Using gulpfile ~/code/famous-angular-yo/gulpfile.js
[16:47:07] Starting 'cordova:run'...
[16:47:07] Running task 'cordova:run' with targets phonemonitor in mode dev
[16:47:07] Starting 'cordova:run:GW3wv'...
[16:47:07] ionic run android
[16:47:07] Finished 'cordova:run:GW3wv' after 6.26 ms
[16:47:07] Finished 'cordova:run' after 21 ms
[16:47:07] An error occured executing a command line action
```
and repo is [here](https://github.com/mydearxym/famous_angular_ionic)

**Comment by thaiat** [comment]
try to navigate in your dist folder for your mobile target, and at the right level (above www folder) run manually the cordova command: cordova run android

**Comment by mydearxym** [comment]
should't i add android platform first ? like `cordova platform add android` or something?

**Comment by thaiat** [comment]
yes you should.
gulp cordova:run is only distributing the sources and then executing cordova in the proper dist folder
so you have to install the platforms manually

sub sequent runs will not destroy dist so it should be a one operation

**Comment by mydearxym** [comment]
is kinda  awkward -- could tell me where to run this `cordova platform add android`? 
i get this error everywhere in my project dir ...
```javascript 
Current working directory is not a Cordova-based project.
```

**Comment by thaiat** [comment]
sure it should be in dist/phonemonitor/dev

**Comment by mydearxym** [comment]
but my file structure is like this,  need i mkdir myself ?

```bash
~/code/famous-angular-yo :)$ tree dist/
dist/
└── app
    └── dev
        ├── 404.html
        ├── favicon.ico
        ├── fonts
        │   ├── FontAwesome.otf
        │   ├── fontawesome-webfont.eot
        │   ├── fontawesome-webfont.svg
        │   ├── fontawesome-webfont.ttf
        │   ├── fontawesome-webfont.woff
        │   ├── glyphicons-halflings-regular.eot
        │   ├── glyphicons-halflings-regular.svg
        │   ├── glyphicons-halflings-regular.ttf
        │   ├── glyphicons-halflings-regular.woff
        │   ├── ionicons.eot
        │   ├── ionicons.svg
        │   ├── ionicons.ttf
        │   └── ionicons.woff
        ├── index.html
        ├── robots.txt
        ├── scripts
        │   └── bundle.js
        └── styles
            └── main.css
```

**Comment by thaiat** [comment]
ok you have to gulp dist --target phonemonitor

**Comment by mydearxym** [comment]
it's embarrassed .. i just can't run ` cordova run android/ios` to launch the emulator , all kinds of errors which i am tired to resolve (i can launch them in android studio and xcode6 ). 
so it's there a way to just build the apk?  and for debug, can i use chrome's develop tools instead?

**Comment by thaiat** [comment]
have you tried creating a cordova project from scratch and executing run?

**Comment by mydearxym** [comment]
it seems worked when i run ` gulp dist --target phonemonitor --platform android` and  `gulp cordova:run --target phonemonitor --platform android` it give me the `apk` file , however when i install it on my phone , it only shows the home index and the hello message from the controller is missing (but the web version works fine ),  did i do something wrong?

**Comment by thaiat** [comment]
try debug the app on your phone, as it is not related to the generator anymore i m closing the issue
