### ISSUE TITLE
ng-click not work!

### ISSUE THREAD

**Issue by mydearxym** [thaiat/generator-angular-famous-ionic#130]
hi @thaiat , sorry to bother you again ~
i recently integrated angular-material in my project and it's works great, but the ng-click seems not work as normal , i tried lot ways and just not right(not the angular-material's problem)
__for example__ i add a `callme`function in helloCtrl and bind it in front view

```javascript
'use strict';
var controllername = 'hello';

module.exports = function (app) {
  /*jshint validthis: true */
  var deps = [];

  function controller() {
    var vm = this;
    vm.message = 'hello famous';
    vm.callme = function(){
      alert("dude, show me please");
    }
    var activate = function () {
    };
    activate();
  }
  controller.$inject = deps;
  app.controller(app.name + '.' + controllername, controller);
};

```
```html
<h2 ng-controller="main.common.hello as helloCtrl">
  <span ng-click="helloCtrl.callme()">{{helloCtrl.message}}</span>
</h2>

```
turns out helloCtrl.message works normal , but the `helloCtrl.callme()` just not work even i use this: `ng-click="alert('hello')"`.

i know is sound stupid but it drives me crazy...  any advice will be thankful!

**Comment by mydearxym** [comment]
sorry i clean the cache of my browser and it's works fine .... great!

**Comment by thaiat** [comment]
:+1:
