### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by atgillette** [thaiat/generator-angular-famous-ionic#132]
Hi Avi,

I'm interested in using Intel's XDK for building Cordova applications and was wondering how I'd integrate it in the development workflow.  Any suggestions?

Adrian

**Comment by thaiat** [comment]
I'm not familiar with Intel's XDK...,  but when you gulp dist your mobile app, you end up with a cordova app in the dist folder. There you should be able to integrate XDK

Hope it helps...
