### ISSUE TITLE
npm install fails due to peer dependency error

### ISSUE THREAD

**Issue by flpmorais** [thaiat/generator-angular-famous-ionic#133]
Npm install failed because package peer dependencies for generator-angular-famous-ionic are set to "yo >= 1.2.1" and "generator-sunlime >= 1.5.5" , BUT, generator-sublime 1.5.5 peer dependencies are set to "yo >= 1.0.0", which generates a sibling dependencies not matching error during npm install.

To test if that was the issue, I forked the repo, corrected the line in package.json to "yo >= 1.0.0" and installed it and it worked fine.

I'm using npm 1.3.10 and I have both yo and generator-sublime installed on the latest versions.

**Comment by thaiat** [comment]
hi, thks for that, do you mind doing a PR ?

**Comment by flpmorais** [comment]
sure
