### ISSUE TITLE
Snake case

### ISSUE THREAD

**Issue by raibutera** [thaiat/generator-angular-famous-ionic#144]
Incredible generator, has really made my life as a developer easier.

However, some of the conventions used are not in line with popular angular style practices, including this generator's use of camel case for filenames.

I want to fork and customize the generator to produce files with snake case instead of camel case. 

So that I cover all bases, where should I look to be making alterations?

**Comment by thaiat** [comment]
Hi @raibutera ,

Thanks for the kind words

It should be too hard to do that.
i may implement an option for choosing camel or snake case


i believe the place to change that is in `class/component.js`
the `writing` function is used by most of the sub generators, i would change the name there

Anything else you would change ?


Cheers

Avi

**Comment by raibutera** [comment]
As per the style guidelines I would also add a suffix (e.g. `.directive`, `.ctrl`, `.service`)  to the filenames of generated files. 

However, I saw that you decided this would be a bad idea in #25 

I will add this to my fork if possible.

I noticed that you intend to add an option for snake-casing - how are you handling options? Does it have something to do with .yo-rc? I may be able to help you get it implemented if I understand a little better.

**Comment by thaiat** [comment]
implementation is in progress, should be release next week, still testing it
there will be an option `filenameCase` (camel or snake) in the .yo-rc.json,
option is created when you first scaffold the project or can be manually added aferwards if you decide to work on an existing project with the latest version of the generator

look at PR #147 for more info

as for #25, files are already in folder with component name, i find it redundant to repeat component name, you already know where you are

**Comment by raibutera** [comment]
Great, that's awesome news. I'm genuinely excited! When the feature is released I may write a quick gulp task that will rename existing camel case files to snake case and vice versa. It will be useful for those of us like myself who want to switch. 




I will read the yeoman docs and see how options are used, thanks for the heads up. 






Rai

**Comment by jskrzypek** [comment]
Hey @raibutera, after thinking about it some more we're going to add a `--componentTypeSuffix` flag with which you can ask for your components to be scaffolded with the `name.type.js` convention (though they'll still use the existing `generator-angular-famous-ionic` folder-by-type-by-feature structure)

**Comment by jskrzypek** [comment]
@raibutera, the latest release `v1.3.14` has the new code. Please let us know what you think.

**Comment by raibutera** [comment]
updating my project now, just checking that I properly understand migration:

0. will there be any foreseeable problems when a project already has camel case files and it is switched to snake case?
1. should I create a separate issue for upgrading existing projects? 
2. Will this work fine?
    1. `npm update -g generator-angular-famous-ionic generator-sublime`
    2. (from within project directory) `yo angular-famous-ionic`
    3. select snake-case 
    4. generate a new file

**Comment by raibutera** [comment]
also - absolutely fantastic news that the generator now uses filename suffixes!

**Comment by jskrzypek** [comment]
It should be much simpler than that.

1. There should not be any complications with upgrading the generator over a new project. The default values used by the subgenerators for the `filenameCase` and `filenameSuffix` parameters are `"camelCase"` and `false`, giving you the same default output as was previously the case. If you do run across any issues, please update us.
1. This issue is currently closed. If you have an issue with upgrading an existing project that originates in PR #147 and stems from the case or suffix implementation, definitely feel free to re-open this issue. If the issue comes from something else it's probably best to create a new one. Try it out first, though, because I doubt you'll actually run into trouble while upgrading.  
1. As for what you should actually do to migrate: 
  1. Just run the `npm update -g ...`. It should all still work off the bat. If you're changing the parameters for case or suffixes then do the following steps as well.
  1. Edit your `.yo-rc.json` to add these properties:
    * `"filenameCase": "snake"` for snake-case (for camelCase, set to `"camel"`)
    * `"filenameSuffix": true` (`true` will enable suffixes and `false` will disable them)
  1. Go through and fix up your existing filenames to look however you want them to look. Then run `yo angular-famous-ionic:require`. This will rewire your app together to match the new filenames. The angular namespace names never changed in the first place, so there's nothing to worry about on that score.

A couple of other points: 
* You won't need to run the `yo angular-famous-ionic` command again unless you're using the generator to scaffold a whole new app/project (since it's really a shortcut for `yo angular-famous-ionic:app`). 
* There's nothing aside from your own sanity that means you need to make all of your filenames follow the same convention. All of the files are automatically wired together and managed by browserify so as long as the `require`s point to the right files you're all good. The handy thing is that the `require` subgenerator takes care of this for you and automagically crawls through your client folder and fixes up the `require`s as needed. Since the `require` subgenerator only cares about making sure that the `.js` files in the tree are required by their sibling `index.js` files, it doesn't care about the filename formats  or if they're consistent.

**Comment by raibutera** [comment]
## Issues
> If you do run across any issues, please update us.
I've got an existing project that (used) suffix-less files. When generating new files using the optional suffixes, the generator injects assuming that there is an 'index.js' file not an 'index.module' file. This occurs in both the app scripts (e.g: in main.js `require("../modulename") fixed by require("../modulename/index.module")` and generated test file (`require("../")('app')` - I fix this manually `require("../index.module")('app')`)

My suggested solution to this would be to _not_ suffix module files (as modulename/index.js is obvious, and it keeps require statements clean, whilst preserving suffixes). Of course, this may not sit well with you, so we could also fix the injection logic to append '/index.module'.




## PS: useful script for anyone wanting to change from camel to snake case

```javascript
/**
 * gulp_tasks/tasks/snake-case.js
 * Gulp Task that converts a camelCase generator-angular-famous-ionic app to
 */

'use strict';

// DEPENDENCIES
var _ = require('lodash');
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var fs = require('fs');
var path = require('path');

var helper = require('../common/helper');
var constants = require('../common/constants')();


// constants
var LOCAL = {
    SUFFIXES: ['controller', 'service', 'states', 'directive'], // recognised suffixes
    TYPES: ['controllers', 'services', 'states', 'directives'], // directory names
    PRESERVE: ['index', 'helper', 'helpers'] // do not rename any files with filenames containing these
};

function snakeCaseRename (){
    var scriptsDir = path.join(constants.clientFolder, 'scripts');

    function getFilenameParts (input){
        return _.words(input, /[^\.]+/g);
    }

    var isSuffix = function(input){
        return _.contains(LOCAL.SUFFIXES, input);
    };

    function filenameInfo (input){
        var parts = getFilenameParts(input);
        var partsLength = parts.length;
        var base = parts[0];
        var isJS = (parts[partsLength - 1] === 'js');
        var isHTML = (!isJS && parts[partsLength - 1] === 'html');
        var isTest = (isJS && parts[partsLength - 2] === 'test');
        var hasSuffix = ( isJS && (
                            (!isTest && isSuffix(parts[partsLength - 2])) ||
                            (isTest && isSuffix(parts[partsLength - 3]))
                            )
                        );

        var info = {
            original: input,
            parts: parts,
            name: base,
            js: isJS,
            html: isHTML,
            test: isTest,
            suffix: hasSuffix
        };

        return info;
    }

    function makeNewName (input, type){
        if(!input || !type || !input.original || !input.name){
            throw new Error('could not make new name because missing input or type');
        } else {
            if(input.suffix){
                console.log(input.original + ' already has suffix');
                return false;
            } else {
                if(input.js){
                    input.name = _.kebabCase(input.name);
                    input.name = input.name + '.' + type;

                    if (!input.test) {
                        console.log(input.original + ' -> ' + input.name + '.js');
                        return input.name + '.js';
                    } else {
                        console.log(input.original + ' -> ' + input.name + '.test.js');
                        return input.name + '.test.js';
                    }
                } else if (input.html){
                    input.name = _.kebabCase(input.name);
                    console.log(input.original + ' -> ' + input.name + '.html');
                    return input.name + '.html';
                } else {
                    console.log(input.original + ' is not a js/html file');
                    return false;
                }
            }
        }
    }

    function directoriesOnly (value, key, collection) {
        return _.indexOf(value, '.') === -1;
    }

    var moduleNames = _.filter(fs.readdirSync(scriptsDir), directoriesOnly);

    console.log('Renaming files in modules ', moduleNames.join(', '));

    // loop over each module
    _.forEach(moduleNames, function (dirname) {
        var modulePath = path.join(scriptsDir, dirname);

        var subdirs = _.filter(_.filter(fs.readdirSync(modulePath), directoriesOnly), function (value, key, collection) {
            return _.contains(LOCAL.TYPES, value);
        });

        console.log('\n\nrenaming ' + subdirs.join(', ') + ' files in ' + dirname);

        // loop over sub directories, ie. controllers, directives, services...
        _.forEach(subdirs, function (subdirname) {
            console.log('\n' + dirname + '/' + subdirname + ':');

            var subdirPath = path.join(modulePath, subdirname);

            // we only want files
            var subdirContents = _.filter(fs.readdirSync(subdirPath), function (value, key, collection) {
                return _.indexOf(value, '.') !== -1;
            });

            // loop over files inside subdirectory
            _.forEach(subdirContents, function (currentFile) {
                var current = filenameInfo(currentFile);

                if (_.contains(LOCAL.PRESERVE, current.name)) { // file is protected
                    console.log('leaving ' + current.name + ' alone.');
                } else { // we need to check if we need to rename this file
                    var newName = makeNewName(current, subdirname.substr(0, subdirname.length - 1));

                    if(newName){
                        fs.renameSync(path.join(subdirPath, currentFile), path.join(subdirPath, newName));
                    }
                }
            });
        });
    });

    console.log('\n' + 'Renamed all files where necessary.\nPLEASE RUN yo angular-famous-ionic:require TO FIX DEPENDENCY INJECTION');
}

gulp.task('snakeConvert', snakeCaseRename);

```

### Usage:
1. save as snake-case.js in `gulp_tasks/tasks/`
2. `gulp convertCase`
3. `yo angular-famous-ionic:require`

Please note that you will have to update any references in directives to renamed HTML files.

**Comment by raibutera** [comment]
@thaiat I can't reopen this issue, but please check the first part of above (regarding index.module)

**Comment by thaiat** [comment]
@raibutera, i am aware of the issue and a PR is on its way to fix it
