### ISSUE TITLE
correct way to add cordova plugins

### ISSUE THREAD

**Issue by stefanwuthrich** [thaiat/generator-angular-famous-ionic#152]
Hi
First tks for you really great generator.
I have a question about the correct workflow to add additional cordova plugins.
I have a working mobile app, which i can successfully start with:
gulp browsersync --t mobile --platform android OR  gulp cordova:run --target mobile --platform android 
now i want to add additional cordova plugins, and did add them to
reps/io-infon-app/client/cordova/mobile/hooks/after_platform_add/010_install_plugins.js
eg:
```
var pluginlist = [
    'org.apache.cordova.device',
    'org.apache.cordova.device-motion',
    'org.apache.cordova.device-orientation',
    'org.apache.cordova.geolocation',
    'org.apache.cordova.console',
    'com.ionic.keyboard',
    'nl.xservices.plugins.SocialSharing'
];
```

but this dont add anything to the path, running the app
reps/io-infon-app/dist/mobile/dev/plugins

doing a new  gulp dist --t mobile --mode dev
dont add nothing also.

for sure i miss something. I must add the plugins in the js and manually to the dist folder or should i use cordova plugin add this way: cordova plugin add org.apache.cordova.camera and then add it to the hooks js ?

**Comment by thaiat** [comment]
you should add your plugin using the `cordova plugin add` command.
The hook file `010_install_plugins.js` purpose is only to capture the list of plugins for another dev getting the repo.
So each time you are happy with the installed plugin modify the hook file to add it the list.

Does this make sense ?

**Comment by stefanwuthrich** [comment]
Hi.tks for your answer.
Yep.make sense
Am 06.04.2015 23:00 schrieb Avi Haiat <notifications@github.com>:you should add your plugin using the cordova plugin add command.
The hook file 010_install_plugins.js purpose is only to capture the list of plugins for another dev getting the repo.
So each time you are happy with the installed plugin modify the hook file to add it the list.

Does this make sense ?
