### ISSUE TITLE
Using a fresh installation on Node.js 10.x, failure

### ISSUE THREAD

**Issue by bdeanindy** [thaiat/generator-angular-famous-ionic#153]
Just trying to use the:
```
gulp lint
```

This application scaffolding fails with the following:

bdean@Benjamins-MacBook-Pro-3:~/SparkPost/ASSETS/ngSparkPostWebhookConsumer (HEAD: ref: refs/heads/master) $ gulp lint
[05:22:54] Using gulpfile ~/SparkPost/ASSETS/ngSparkPostWebhookConsumer/gulpfile.js
[05:22:54] Starting 'static'...
[05:22:55] Error in plugin 'gulp-jscs'
Message:
    Operator , should not stick to following expression at main.js :
     6 |require('angular-ionic');
     7 |require('angular-material');
     8 |var app = angular.module(namespace, ['ionic','ngMaterial',
-----------------------------------------------------^
     9 |    // inject:modules start
    10 |    // inject:modules end
[05:22:55] 
/Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/public/scripts/main.js
  8:44  error  A space is required after ','  comma-spacing
  8:57  error  Unexpected trailing comma      comma-dangle

/Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/gulp_tasks/tasks/test.js
  33:20  warning  Don't use process.exit(); throw an error instead  no-process-exit

✖ 3 problems (2 errors, 1 warning)

[05:22:55] 'static' errored after 1.04 s
[05:22:55] ESLintError in plugin 'gulp-eslint'
Message:
    A space is required after ','.
Details:
    fileName: /Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/public/scripts/main.js
    lineNumber: 8
[05:22:55] lint failed

/Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/gulp_tasks/tasks/lint.js:174
                throw new Error('lint_error');
                      ^
Error: lint_error
    at DestroyableTransform.<anonymous> (/Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/gulp_tasks/tasks/lint.js:174:23)
    at DestroyableTransform.emit (events.js:117:20)
    at /Users/bdean/SparkPost/ASSETS/ngSparkPostWebhookConsumer/node_modules/gulp-eslint/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickDomainCallback (node.js:486:13)

**Comment by thaiat** [comment]
this is due to the fact that you don't have yet scaffolded any module.
once you will the error will go away as the module name will be injected after the comma.
