### ISSUE TITLE
gulp browsersync crash   throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by heralight** [thaiat/generator-angular-famous-ionic#167]
Hi!

Very good generator!
I'm new to your generator, after  generate a new project has in your readme, I launch it with gulp browserync and I get:

[00:09:31] Starting 'browsersyncstart'...
[00:09:31] Starting 'browsersyncstart:2R3y6'...
[00:09:31] Finished 'browsersyncstart:2R3y6' after 29 ms
[00:09:31] Finished 'browsersyncstart' after 36 ms
[BS] Access URLs:
 -------------------------------------
       Local: http://localhost:5000
    External: http://192.168.1.25:5000
 -------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.1.25:3001
 -------------------------------------
[BS] Serving files from: ./dist/app/dev
[BS] Watching files...
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn google chrome ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickDomainCallback (node.js:381:11)

I don't have any other node instance or any listener on this port ...
> netstat -tulpn | grep 5000
> netstat -tulpn | grep 3001
>

an other project with browsersync, generator-gulp-angular, run well..

do you have any idea please?

Alexandre

**Comment by heralight** [comment]
Apparently it's related on how browsersync is used.
On generator-gulp-angular with same version all is ok.
In generator-angular-famous-ionic with versin browsersync 2.1.6 or 2.6.9 or 2.2.4 same problem.

But if in node_modules/browser-sync/lib/internal-events.js I comment 

 if (data.type !== "snippet") {
              //  utils.openBrowser(data.url, bs.options);
            }

line 40 , it's runnning well but browser doesn't open automatically.

strange

**Comment by thaiat** [comment]
looks like `browsersync` can't open `google` with spawn
On what OS are you ?

Maybe on your OS the name of the browser is different from the one used in `gulp_tasks/common/constants.js` -> serve.browser

You can try another name (`chrome` instead of `google chrome` or `firefox, or you can set `open` to false and open your browser manually)

**Comment by heralight** [comment]
Thank you! I changed 'browser' to firefox and it's working well now. Anyway it's strange, I have chrome installed on a ubuntu os ...

**Comment by mauroavello** [comment]
Just wanted to mention that i used 'google-chrome' and it worked for me.
Mint 17.1 (ubuntu 14.10)

**Comment by thaiat** [comment]
@mauroavello thanks for the update
