### ISSUE TITLE
Bundle.js not rebuilding

### ISSUE THREAD

**Issue by adriangith** [thaiat/generator-angular-famous-ionic#170]
When I update `client/scripts/main.js`,  `bundle.js` does not live rebuild while using `gulp browsersync`. I have to stop the server and restart it.

**Comment by thaiat** [comment]
i can t reproduce
what version are u using ? (generator-angular-famous-ionic and generator-sublime)

**Comment by adriangith** [comment]
I'm using Docker with a Virtualbox shared folder and after doing more research, I know that the problem is with Docker and not with your generator.
