### ISSUE TITLE
ng-annotation support?

### ISSUE THREAD

**Issue by lanocturne** [thaiat/generator-angular-famous-ionic#187]
Just wander is it possible to add 'browserify-ngannotate' to the gulp task? 

Sometimes it's driving me nuts to write DIs at deps array, modal controllers etc, again and again.

**Comment by thaiat** [comment]
hi @lanocturne 
i don't see how ng-annotate will work correctly as the generator uses namespace for angular components

i.e when you define a new controller 'home' in the 'common' module, the name of the controller is:
'app.common.home'

Because of the dots you need to use DI with deps array....

**Comment by lanocturne** [comment]
Got cha. Thanks for the answer @thaiat :)
