### ISSUE TITLE
sharing directives between modules

### ISSUE THREAD

**Issue by toppetoppe** [thaiat/generator-angular-famous-ionic#202]
Could anyone show an example of sharing directives between modules?
I have gotten sharing services between modules to work but not directives.

**Comment by jskrzypek** [comment]
Angular is is cool in that you usually shouldn't need to share directives between modules, since you don't need to inject the javascript.

Simply make sure the module with the directive is required by the module consuming them and then ask for the directives in your HTML.

**Comment by toppetoppe** [comment]
I tried the following without success.

I have a common module that depends on a layout module eg.

```javascript
var layout = require('../layout')(namespace);

var app = angular.module(fullname, ['ui.router', 'ionic', 'famous.angular', 'ngCordova', 'ngMaterial', layout.name]);
```
The directive is called mvHeader (was scaffolded using the generator) and nothing happens when i write <mvHeader></mvHeader> in my html

**Comment by thaiat** [comment]
can you put together a simple repo so I can have a look

**Comment by toppetoppe** [comment]
https://github.com/toppetoppe/angular-famous-ionic-example

**Comment by thaiat** [comment]
your directive should be mv-header in the view not mvHeader

**Comment by thaiat** [comment]
here :https://github.com/toppetoppe/angular-famous-ionic-example/blob/master/client/scripts/common/views/home.html#L6

**Comment by toppetoppe** [comment]
ah, thanks!

**Comment by thaiat** [comment]
thks for the kind words
