### ISSUE TITLE
ERROR : Cannot read property 'navigator' of undefined

### ISSUE THREAD

**Issue by LunarDevelopment** [thaiat/generator-angular-famous-ionic#208]
Hello! 

I've looked and this seems to be a unique issue.. 

I've used this generator a couple of times and whenever I follow the process to make a new app, I'll then attempt to either run gulp browserify or open the dist folder on local host and get the below error in the web browser console: 
``` 
Uncaught TypeError: Cannot read property 'navigator' of undefined
```
I'm aware that navigator is the browser's GPS helper however I'm clueless as to why this error is appearing on a fresh build of the app. 

EDIT: 

Tracked down where this is coming from: 

```
  var self = ionic.Platform = {

    // Put navigator on platform so it can be mocked and set
    // the browser does not allow window.navigator to be set
    navigator: window.navigator,
``` 

..\..\bower_components\ionic\release\js\ionic.js:2068

Lewis

**Comment by thaiat** [comment]
window should not be undefined 

can you put together a repo with exact steps for reproduction ?

**Comment by LunarDevelopment** [comment]
I would love to but I don't really have the time at the moment (I'll try to make time later) 

My steps are as defined in readme:  

``` 
mkdir ngTaxi && cd ngTaxi 
yo angular-famous-ionic
yo angular-famous-ionic:module common
yo angular-famous-ionic:controller common hello
gulp browsersync
``` 

It must be something to do with my environment but its an odd issue to troubleshoot.

**Comment by thaiat** [comment]
several questions:
- what's your environment ?
- what version of the generator are you using ?
- where do you get the error ?
- what browser do you use ?

**Comment by LunarDevelopment** [comment]
Windows 7 64 bit. 
Google Chrome - latest 
I get the error in chrome console 
```
Uncaught TypeError: Cannot read property 'navigator' of undefined
```

And this error in IE - Latest 

```
SCRIPT5007: Unable to get property 'navigator' of undefined or null reference
``` 

generator: 
```
"name": "generator-angular-famous-ionic",
 "version": "1.5.9",
 ```
```
NPM : 2.10.1
node : 0.12.4 
```
I've just noticed there's an update available for the generator so I'll update now to test the latest.. 

P.s.

Thankyou for taking an interest!

**Comment by thaiat** [comment]
@LunarDevelopment , i don't think the latest is going to impact this issue
if you have a moment we can skype or do a google hangout

**Comment by LunarDevelopment** [comment]
Hm, I dont have a microphone handy. 

During update of the generator I've got an error stating : 
```
peerinvalid Peer gereator-angular-famous-ionic@1.6.2 wants generator-sublime@>=1.8.1 
```
So I'll update Sublime and monitor npm logs to try and get a perfect install then start a new project. 

Failing that I'll create a repo like you initially suggested and post the link back here. 

Thanks!

**Comment by LunarDevelopment** [comment]
PRAISE THE SUN! 

I've updated my generator, yeoman, generator-sublime and reran a fresh install which is working fine now! 

Thanks for all the help, it was very good of you. 

Lewis

**Comment by thaiat** [comment]
glad it's working
